-- Migration 049: concrete solution_graph sketches for calculus tutorial parts (migrations 043-048).
-- Generated by backend/gen049.ts (compiled through the real compileGraph; points validated on-curve).
-- Abstract derivative-graph sketches (4.2 Q2, Q5) are left sketch-only per skills.md (no faithful stand-in).

-- cc21800c-0000-0000-0000-000000000000  part[2] (iii): parametric loop segment; endpoints (0,0) & (-sqrt3/2,-sqrt3/2), min (-sqrt2/2,-1)
UPDATE questions
SET parts = jsonb_set(parts, '{2,solution_graph}', $${"x_range":[-1,0.25],"y_range":[-1.2,0.3],"curves":[{"x_expr":"sin(t)","y_expr":"sin(2*t)","domain":[-1.0471975511965976,0],"label":"C"}],"points":[{"x":0,"y":0,"label":"(0,\\ 0)","kind":"point"},{"x":-0.8660254037844386,"y":-0.8660254037844386,"label":"\\left(-\\tfrac{\\sqrt3}{2},\\ -\\tfrac{\\sqrt3}{2}\\right)","kind":"point"},{"x":-0.7071067811865476,"y":-1,"label":"\\left(-\\tfrac{\\sqrt2}{2},\\ -1\\right)","kind":"min"}]}$$::jsonb)
WHERE id = 'cc21800c-0000-0000-0000-000000000000' AND parts->2->>'label' = 'iii';

-- cc219009-0000-0000-0000-000000000000  part[0] (i): f(x)=e^x sin x on [-3,3]
UPDATE questions
SET parts = jsonb_set(parts, '{0,solution_graph}', $${"x_range":[-3.3,3.3],"y_range":[-1,8],"curves":[{"expr":"e^x*sin(x)","domain":[-3,3],"label":"y=e^x\\sin x"}],"points":[{"x":0,"y":0,"label":"O","kind":"intercept"}]}$$::jsonb)
WHERE id = 'cc219009-0000-0000-0000-000000000000' AND parts->0->>'label' = 'i';

-- cc219009-0000-0000-0000-000000000000  part[2] (iii): f and its cubic Maclaurin polynomial g on [-3,3]
UPDATE questions
SET parts = jsonb_set(parts, '{2,solution_graph}', $${"x_range":[-3.3,3.3],"y_range":[-4,22],"curves":[{"expr":"e^x*sin(x)","domain":[-3,3],"label":"y=f(x)"},{"expr":"x+x^2+x^3/3","domain":[-3,3],"label":"y=g(x)"}],"points":[{"x":0,"y":0,"label":"O","kind":"intercept"}]}$$::jsonb)
WHERE id = 'cc219009-0000-0000-0000-000000000000' AND parts->2->>'label' = 'iii';

-- cc21b004-0000-0000-0000-000000000000  part[0] (i): periodic piecewise: xe^x on (0,1], e(2-x) on (1,2], period 2
UPDATE questions
SET parts = jsonb_set(parts, '{0,solution_graph}', $${"x_range":[-2.3,4.3],"y_range":[-0.5,3.2],"curves":[{"expr":"(x+2)*e^(x+2)","domain":[-2,-1]},{"expr":"-e*x","domain":[-1,0]},{"expr":"x*e^x","domain":[0,1]},{"expr":"e*(2-x)","domain":[1,2]},{"expr":"(x-2)*e^(x-2)","domain":[2,3]},{"expr":"e*(4-x)","domain":[3,4]}],"points":[{"x":-2,"y":0,"kind":"intercept"},{"x":-1,"y":2.718281828459045,"label":"(-1,\\ e)","kind":"point"},{"x":0,"y":0,"label":"O","kind":"intercept"},{"x":1,"y":2.718281828459045,"label":"(1,\\ e)","kind":"point"},{"x":2,"y":0,"label":"(2,\\ 0)","kind":"intercept"},{"x":3,"y":2.718281828459045,"kind":"point"},{"x":4,"y":0,"kind":"intercept"}]}$$::jsonb)
WHERE id = 'cc21b004-0000-0000-0000-000000000000' AND parts->0->>'label' = 'i';

-- cc21c001-0000-0000-0000-000000000000  part[1] (b): y=5x^2-x^3+100; min (0,100), max (10/3, 118.52)
UPDATE questions
SET parts = jsonb_set(parts, '{1,solution_graph}', $${"x_range":[-2.3,5.3],"y_range":[90,135],"curves":[{"expr":"5*x^2-x^3+100","domain":[-2,5],"label":"y=5x^2-x^3+100"}],"points":[{"x":0,"y":100,"label":"(0,\\ 100)","kind":"min"},{"x":3.3333333333333335,"y":118.51851851851852,"label":"\\left(\\tfrac{10}{3},\\ \\tfrac{3200}{27}\\right)","kind":"max"}]}$$::jsonb)
WHERE id = 'cc21c001-0000-0000-0000-000000000000' AND parts->1->>'label' = 'b';

-- cc21c002-0000-0000-0000-000000000000  part[1] (b): y=1-1/(x+1); VA x=-1, HA y=1, through origin
UPDATE questions
SET parts = jsonb_set(parts, '{1,solution_graph}', $${"x_range":[-6,6],"y_range":[-4,4],"curves":[{"expr":"1-1/(x+1)","domain":[-6,6],"label":"y=1-\\dfrac{1}{x+1}"}],"asymptotes":[{"kind":"vertical","x":-1,"label":"x=-1"},{"kind":"horizontal","expr":"1","label":"y=1"}],"points":[{"x":0,"y":0,"label":"O","kind":"intercept"}]}$$::jsonb)
WHERE id = 'cc21c002-0000-0000-0000-000000000000' AND parts->1->>'label' = 'b';

-- cc21c007-0000-0000-0000-000000000000  part[2] (iii): L=50e^{kt}, k=0.2 representative; through (0,50)
UPDATE questions
SET parts = jsonb_set(parts, '{2,solution_graph}', $${"x_range":[-0.5,8.5],"y_range":[0,260],"curves":[{"expr":"50*e^(0.2*x)","domain":[0,8],"label":"L=Ae^{kt}"}],"points":[{"x":0,"y":50,"label":"(0,\\ 50)","kind":"point"}],"x_label":"t","y_label":"L"}$$::jsonb)
WHERE id = 'cc21c007-0000-0000-0000-000000000000' AND parts->2->>'label' = 'iii';

-- cc21c008-0000-0000-0000-000000000000  part[2] (iii): logistic; through (0,20), HA P=100
UPDATE questions
SET parts = jsonb_set(parts, '{2,solution_graph}', $${"x_range":[-0.3,4.3],"y_range":[0,110],"curves":[{"expr":"100/(1+4*e^(-2*x))","domain":[0,4],"label":"P=\\dfrac{100}{1+4e^{-2t}}"}],"asymptotes":[{"kind":"horizontal","expr":"100","label":"P=100"}],"points":[{"x":0,"y":20,"label":"(0,\\ 20)","kind":"point"}],"x_label":"t","y_label":"P"}$$::jsonb)
WHERE id = 'cc21c008-0000-0000-0000-000000000000' AND parts->2->>'label' = 'iii';

-- cc21c009-0000-0000-0000-000000000000  part[2] (c): theta=20-10e^{-t/10}; through (0,10), HA theta=20
UPDATE questions
SET parts = jsonb_set(parts, '{2,solution_graph}', $${"x_range":[-1,42],"y_range":[0,24],"curves":[{"expr":"20-10*e^(-x/10)","domain":[0,40],"label":"\\theta=20-10e^{-t/10}"}],"asymptotes":[{"kind":"horizontal","expr":"20","label":"\\theta=20"}],"points":[{"x":0,"y":10,"label":"(0,\\ 10)","kind":"point"}],"x_label":"t","y_label":"\\theta"}$$::jsonb)
WHERE id = 'cc21c009-0000-0000-0000-000000000000' AND parts->2->>'label' = 'c';

